//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


using CMS.Base.Web.UI;
using CMS.FormEngine.Web.UI;

public partial class CMSModules_AcceleratedMobilePages_Default {
    
    /// <summary>
    /// LabelEnableAmp control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected LocalizedLabel LabelEnableAmp;
    
    /// <summary>
    /// chkEnableAmpFilter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected CMSCheckBox chkEnableAmpFilter;
    
    /// <summary>
    /// LabelDefaultCss control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected LocalizedLabel LabelDefaultCss;
    
    /// <summary>
    /// chkDefaultCss control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected CMSCheckBox chkDefaultCss;
    
    /// <summary>
    /// labelSelectCss control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected LocalizedLabel labelSelectCss;
    
    /// <summary>
    /// selectStyleSheet control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected FormControl selectStyleSheet;
}
